server {
    listen 80;
    server_name localhost;

    location /admin {
        root /usr/share/nginx/html;
        index index.html index.htm;
        try_files $uri $uri/index.html $uri/ =404;
    }

    # Redireccionar raíz al subpath /admin
    location = / {
        return 301 /admin;
    }
}
